server:
  port: 9090
logging:
  file: /Users/gzf/IdeaProjects/demoList/web.log
spring:
  application:
    name: testDemo
#  datasource:
#    druid:
#      url: jdbc:mysql://39.105.31.111:3306/spring_boot_lambda?useSSL=false&useUnicode=true&characterEncoding=utf-8
#      username: root
#      password: root
#      driver-class-name: com.mysql.jdbc.Driver
#      db-type: com.alibaba.druid.pool.DruidDataSource
#      initial-size: 5
#      min-idle: 5
#      max-active: 20
#      max-wait: 60000
#      time-between-eviction-runs-millis: 60000
#      validation-query: select 1
#该应用注册到 sentinel 控制台
  cloud:
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080  # 控制台地址



  session:
    store-type: none

